variables:
  GIT_DEPTH: 1

stages:
  - build

build-job:
  image: registry.net.xuegaogg.com/tool/dpdk-builder:v0.3-rk8
  stage: build
  artifacts:
    paths:
      - build/examples
    expire_in: 1 week
  script:
    - meson build -Dexamples=l2fwd -Dplatform=generic -Denable_drivers=net/minixdp,mempool/bucket,mempool/ring,mempool/stack -Ddisable_libs=gpudev,power,vhost -Dmax_lcores=8 -Dtests=false
    - cd build
    - ninja
