variables:
  GIT_DEPTH: 1

stages:
  - build

build-job:
  image: fedora:34
  stage: build
  script:
    # 替换镜像，省点流量
    - mv /etc/yum.repos.d/fedora-cisco-openh264.repo /etc/yum.repos.d/fedora-cisco-openh264.repo.bak
    - |
      cat > /etc/yum.repos.d/fedora.repo << 'EOF'
      [fedora]
      name=Fedora $releasever - $basearch
      failovermethod=priority
      baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/$releasever/Everything/$basearch/os/
      metadata_expire=28d
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      skip_if_unavailable=False
      EOF
    - |
      cat > /etc/yum.repos.d/fedora-updates.repo << 'EOF'
      [updates]
      name=Fedora $releasever - $basearch - Updates
      failovermethod=priority
      baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/$releasever/Everything/$basearch/
      enabled=1
      gpgcheck=1
      metadata_expire=6h
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      skip_if_unavailable=False
      EOF
    - |
      cat > /etc/yum.repos.d/fedora-modular.repo << 'EOF'
      [fedora-modular]
      name=Fedora Modular $releasever - $basearch
      failovermethod=priority
      baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/$releasever/Modular/$basearch/os/
      enabled=1
      metadata_expire=7d
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      skip_if_unavailable=False
      EOF
    - |
      cat > /etc/yum.repos.d/fedora-updates-modular.repo << 'EOF'
      [updates-modular]
      name=Fedora Modular $releasever - $basearch - Updates
      failovermethod=priority
      baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/$releasever/Modular/$basearch/
      enabled=1
      gpgcheck=1
      metadata_expire=6h
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      skip_if_unavailable=False
      EOF
    - dnf makecache

    # 安装构建依赖
    - dnf groupinstall "Development Tools" -y
    - dnf install unzip vim curl wget -y
    - dnf install meson python3-pyelftools python3-pip numactl-devel libbpf-devel libpcap-devel openssl-devel -y
    - pip3 install ninja

    # 构建
    - meson build
    - cd build
    - ninja



